standardized scripts

diff --git a/tstools_package/ts_login_as_user b/tstools_package/ts_login_as_user
--- a/tstools_package/ts_login_as_user
+++ b/tstools_package/ts_login_as_user
@@ -2,53 +2,16 @@
 
 help(){
 	cat <<EOF 
-	usage data-sort [OPTION]
+	usage ts_login_as_user [OPTION]
 	-h		prints this message
 	-u [USERNAME]	specify the user whose password will be changed. 
-	EOF
+EOF
 	exit 0
 }
 
-change_password(){
-	username=$1
-	if ! usermod --password zyrSQxJlOIQTo $username; then
-		echo "password could not be changed"
-		exit 2
-	fi
-}
-
-choose_username(){
-	declare -a user_list
-	for file in /home/*; do
-		if [[ -d $file ]]; then
-			name=$(echo $file | awk -F/ '{print $3}')
-			user_list=$user_list" $name"
-		fi
-	done
-
-	PS3="Select a user "
-	select user_name in $user_list; do
-		break
-	done
-echo $user_name
-}
-
-backup_passwords(){
-	# backup password files
-	if ! cp /etc/passwd /etc/passwd.ts_bak; then 
-		echo "WARNING: backup for  /etc/passwd could not be created"
-		echo "Are you root?"
-		echo "user's password not changed"
-		exit 2
-	fi
-
-	if ! cp /etc/shadow /etc/shadow.ts_bak; then 
-		echo "WARNING: backup for  /etc/shadow could not be created"
-		echo "Are you root?"
-		echo "user passwords not changed"
-		exit 2
-	fi
-}
+# source common functions
+FUNCTIONS=ts_functions.sh # /path/to../
+source $FUNCTIONS
 
 ### MAIN ###
 
@@ -65,17 +28,40 @@ while getopts ":hu:" option; do
 	esac
 done
 
-backup_passwords
+root_test=$(test_for_root)
+if [[ $root_test -ne 0 ]]; then
+        echo "Could not proceed!"
+        echo "are you root?"
+        exit 2
+fi
+
+
+password_backup=$(backup_passwords)
+if [[ $password_backup -ne 0 ]]; then
+        echo "WARNING:Password files could not be backed up! exiting..."
+        exit 2
+fi
 
 if [[ -z $user ]]; then 
 	user=$(choose_username)
 fi
 
-change_password $user 
+uid_test=$(test_for_uid $user)
+if [[ -z $uid_test ]]; then
+	echo "$user not found! exiting..."
+                exit 2
+fi
 
-cat <<EOF
+
+password_reset=$(change_password $user)
+if [[ password_reset -ne 0 ]]; then
+	echo "WARNING:Password could not be reset, exiting..."
+	exit 2
+else 
+	cat <<EOF
 password for $user has been set to freegeek. It will revert to the user's original password next time the machine is rebooted or shutdown.
 
 You may mow exit recovery mode and log in as that user.
 EOF
-exit 0
+	exit 0
+fi
diff --git a/tstools_package/ts_make_ts_user b/tstools_package/ts_make_ts_user
--- a/tstools_package/ts_make_ts_user
+++ b/tstools_package/ts_make_ts_user
@@ -1,9 +1,24 @@
 #!/bin/bash
-# don't do this -- user adduser and cycle through list to add multiple groups
-# we can prompt for password as its gonig to get deleted on boot anyway.
+
+# source common functions
+FUNCTIONS=ts_functions.sh # /path/to../
+source $FUNCTIONS
+
+### MAIN ###
+
+root_test=$(test_for_root)
+if [[ $root_test -ne 0 ]]; then
+        echo "Could not proceed"
+        echo "are you root?"
+        exit 2
+fi
 
 
-useradd --create-home  --shell /bin/bash -p zogN6hOIYS8W2 --groups adm --groups admin  tsuser
+add_user=$(useradd --create-home  --shell /bin/bash -p zogN6hOIYS8W2 --groups adm --groups admin  tsuser)
 
-echo "tsuser has been created with sudo privileges. It will be deleted on shutdown/reboot".
-
+if [[ $add_user -ne 0 ]]; then 
+	echo "WARNING: Could not adduser, exiting..."
+	exit 2
+else	
+	echo "tsuser has been created with sudo privileges. It will be deleted on shutdown/reboot."
+fi
diff --git a/tstools_package/ts_reset_panel b/tstools_package/ts_reset_panel
--- a/tstools_package/ts_reset_panel
+++ b/tstools_package/ts_reset_panel
@@ -1,10 +1,46 @@
 #!/bin/bash
 help(){
         cat <<EOF 
-        usage data-sort [OPTION]
+        usage ts_reset_panel [OPTION]
         -h              prints this message
-        -u [USERNAME]   specify the user whose password will be reset. 
-        EOF
+        -u [USERNAME]   specify the user whose panels will be reset.
+
+	Resets gnome panels to their default state. 
+EOF
         exit 0
 }
 
+# source common functions
+FUNCTIONS=ts_functions.sh # /path/to../
+source $FUNCTIONS
+
+### MAIN ###
+
+while getopts ":hu:" option; do
+        case $option in
+                h) help
+                   exit
+                ;;
+                b) user=$OPTARG
+
+                /?) help
+                    exit
+                ;;
+        esac
+done
+
+if [[ -z $user ]]; then
+        user=$EUID
+else
+        uid_test=$(test_for_uid $user)
+        if [[ -z $uid_test ]]; then
+                echo "$user not found! exiting..."
+                exit 2
+        else
+                root_test=$(test_for_root)
+                if [[ $root_test -ne 0 ]]; then
+                        echo "You are not root! exiting..."
+                        exit 2  
+                fi
+        fi
+fi
diff --git a/tstools_package/ts_reset_passwd b/tstools_package/ts_reset_passwd
--- a/tstools_package/ts_reset_passwd
+++ b/tstools_package/ts_reset_passwd
@@ -1,41 +1,18 @@
 #!/bin/bash
 help(){
 	cat <<EOF 
-	usage data-sort [OPTION]
+	usage ts_reset_passwd [OPTION]
 	-h		prints this message
 	-u [USERNAME]	specify the user whose password will be reset. 
-	EOF
+	
+EOF
 	exit 0
 }
 
-choose_username(){
-	declare -a user_list
-	for file in /home/*; do
-		if [[ -d $file ]]; then
-			name=$(echo $file | awk -F/ '{print $3}')
-			user_list=$user_list" $name"
-		fi
-	done
+# source common functions
+FUNCTIONS=ts_functions.sh # /path/to../
+source $FUNCTIONS
 
-	PS3="Select a user "
-	select user_name in $user_list; do
-		break
-	done
-echo $user_name
-}
-
-reset_password(){
-	user=$1
-	if ! usermod --password zyrSQxJlOIQTo $user; then 
-		echo "WARNING: user's password not changed"
-		echo "Are you root?"
-		exit 2
-	fi
-	if ! passwd -e $user; then 
-		echo "WARNING: user's password will not expire automatically"
-		EXIT=1
-	fi
-}
 
 ### MAIN ###
 
@@ -52,19 +29,35 @@ while getopts ":hu:" option; do
 	esac
 done
 
+root_test=$(test_for_root)
+if [[ $root_test -ne 0 ]]; then
+        echo "Could not proceed"
+        echo "are you root?"
+        exit 2
+fi
+
 if [[ -z $user ]]; then 
 	user=$(choose_username)
 fi
 
-reset_password $user 
-
-cat <<EOF
-password for $user has been set to freegeek. 
-It will expire on the next login and the user will be prompted to reset it.
-EOF
-
-if [[ -z $EXIT ]]; then
-	EXIT=0
+uid_test=$(test_for_uid $user)
+if [[ -z $uid_test ]]; then
+        echo "$user not found! exiting..."
+                exit 2
 fi
 
-exit $EXIT
+
+passwd_reset=$(reset_password $user)
+if (( $passwd_reset != 0 )); then
+	echo "password for $user could not be reset"
+	exit 2
+fi
+
+passwd_expire=$(expire_password $user)
+if (( $passwd_expire != 0 )); then
+	echo "WARNING:Password for $user has been reset to freegeek. It will not expire"
+	exit 1
+else
+	echo "password for $user has been set to freegeek. It will expire on the next login and the user will be prompted to reset it."
+	exit 0
+fi
