modified ts_functions with effects 	modified:   ts_functions.sh 	modified:   ts_login_as_user 	modified:   ts_make_ts_user 	modified:   ts_network_backup 	modified:   ts_network_backup_functions.sh 	modified:   ts_rechown 	modified:   ts_reset_panel 	modified:   ts_reset_passwd 	modified:   ts_reset_windowmanager  Untracked files: 	../asus-n13.sh 	../tmp/

diff --git a/tstools_package/ts_login_as_user b/tstools_package/ts_login_as_user
--- a/tstools_package/ts_login_as_user
+++ b/tstools_package/ts_login_as_user
@@ -28,11 +28,11 @@ while getopts ":hu:" option; do
 	esac
 done
 
-root_test=$(test_for_root)
-if [[ $root_test -ne 0 ]]; then
+test_for_root
+if [[ $? -ne 0 ]]; then
         echo "Could not proceed!"
         echo "are you root?"
-        exit 2
+        exit 3
 fi
 
 backup_passwords
@@ -40,24 +40,24 @@ password_backup=$?
 if [[ $password_backup -ne 0 ]]; then
 	echo $password_backup
         echo "WARNING:Password files could not be backed up! exiting..."
-        exit 2
+        exit 3
 fi
 
 if [[ -z $user ]]; then 
 	user=$(choose_username)
 fi
 
-uid_test=$(test_for_uid $user)
-if [[ -z $uid_test ]]; then
-	echo "$user not found! exiting..."
-                exit 2
+test_for_user $user
+if (( $? != 0 )); then
+        echo "$user not found! exiting..."
+        exit 3
 fi
 
 
 password_reset=$(change_password $user)
 if [[ password_reset -ne 0 ]]; then
 	echo "WARNING:Password could not be reset, exiting..."
-	exit 2
+	exit 3
 else 
 	cat <<EOF
 password for $user has been set to freegeek. It will revert to the user's original password next time the machine is rebooted or shutdown.
diff --git a/tstools_package/ts_network_backup b/tstools_package/ts_network_backup
--- a/tstools_package/ts_network_backup
+++ b/tstools_package/ts_network_backup
@@ -90,29 +90,30 @@ while getopts ":hc:r:l:a:A:p:du" option; do
 #sanity checks
 if [[ $create_backup  &&  $restore_backup ]]; then 
 	echo "Only one of the c or r options can be used";
-	exit 2
+	exit 3
 
 elif [[ ! $create_backup && ! $restore_backup ]]; then 
         echo "One of the c or r options must  be used";
-        exit 2
+        exit 3
 
 elif [[ $create_backup  &&  ! $ticket_number ]]; then 
         echo "You must supply a ticket number with the c option";
-        exit 2
+        exit 3
 
 elif [[ $restore_backup && ! $backup_dir ]]; then
         echo "You must supply a backup directory with the r option";
-        exit 2
+        exit 3
 
 elif [[ $data_only  &&  $users_and_data_only ]]; then
         echo "The u or d options are mutually exclusive";
-        exit 2
+        exit 3
 else
 
-	if [[ $(test_for_root) -ne 0 ]]; then
-        	echo "Could not proceed!"
+        test_for_root
+	if [[ $? -ne 0 ]]; then
+		echo "Could not proceed!"
         	echo "Are you root?"
-        	exit 2
+        	exit 3
 	fi
 fi
 # TODO
@@ -202,7 +203,7 @@ elif [[ $restore_backup ]] ; then
 	if [[$? -ne 0 ]]; then
 		echo $backup_passwords_check
 		echo "failed to backup password files ..exiting"
-		exit 2
+		exit 3
 	fi
 
         if [[ $use_log ]]; then
diff --git a/tstools_package/ts_rechown b/tstools_package/ts_rechown
--- a/tstools_package/ts_rechown
+++ b/tstools_package/ts_rechown
@@ -32,23 +32,26 @@ while getopts ":hu:" option; do
 done
 
 
-uid_test=$(test_for_uid $user)
-if [[ -z $uid_test ]]; then
-	echo "$user not found! exiting..."
-        exit 2
+
+test_for_root
+if [[ $? -ne 0 ]]; then
+        echo "You are not root! exiting..."
+        exit 3
 fi
 
-root_test=$(test_for_root)
-if [[ $root_test -ne 0 ]]; then
-        echo "You are not root! exiting..."
-        exit 2
+test_for_user $user
+if (( $? != 0 )); then
+        echo "$user not found! exiting..."
+        exit 3
 fi
+
+
       
 ### reset ownership ###
 
 if ! chown -R $user.$user /home/$user ; then
 	echo "WARNING: Failed to change ownership for some or all files!"
-	exit 2
+	exit 3
 else
 	echo "Changed ownership of $user's files"
 	exit 0
diff --git a/tstools_package/ts_reset_panel b/tstools_package/ts_reset_panel
--- a/tstools_package/ts_reset_panel
+++ b/tstools_package/ts_reset_panel
@@ -3,8 +3,8 @@ help(){
         cat <<EOF 
         usage ts_reset_panel [OPTION]
         -h              prints this message
-        -u [USERNAME]   specify the user whose panels will be reset.
-
+        -u [USERNAME]   specify the user whose panels will be reset,
+			defaults to the user running the command.
 	Resets gnome panels to their default state. 
 EOF
         exit 0
@@ -35,17 +35,16 @@ done
 if [[ -z $user ]]; then
         user=$EUID
 else
-        uid_test=$(test_for_uid $user)
-        if [[ -z $uid_test ]]; then
-                echo "$user not found! exiting..."
-                exit 2
-        else
-                root_test=$(test_for_root)
-                if [[ $root_test -ne 0 ]]; then
-                        echo "You are not root! exiting..."
-                        exit 2  
-                fi
-        fi
+	test_for_user $user
+	if (( $? != 0 )); then
+        	echo "$user not found! exiting..."
+        	exit 3
+	fi
+	test_for_root
+	if [[ $? -ne 0 ]]; then
+		echo "You are not root! exiting..."
+		exit 3  
+      fi
 fi
 
 
@@ -56,7 +55,7 @@ GCONF_RESET=$(set_gconf $user)
 
 $GCONF_RESET /apps/panel
 if [[ $? -ne 0 ]]; then
-	echo "gconf failed to reset" 
+	echo "gconf failed to reset panel" 
 	EXIT=1
 fi
 
diff --git a/tstools_package/ts_reset_passwd b/tstools_package/ts_reset_passwd
--- a/tstools_package/ts_reset_passwd
+++ b/tstools_package/ts_reset_passwd
@@ -29,32 +29,32 @@ while getopts ":hu:" option; do
 	esac
 done
 
-root_test=$(test_for_root)
-if [[ $root_test -ne 0 ]]; then
-        echo "Could not proceed"
+test_for_root
+if [[ $? -ne 0 ]]; then       
+	echo "Could not proceed"
         echo "are you root?"
-        exit 2
+        exit 3
 fi
 
 if [[ -z $user ]]; then 
 	user=$(choose_username)
 fi
 
-uid_test=$(test_for_uid $user)
-if [[ -z $uid_test ]]; then
-        echo "$user not found! exiting..."
-                exit 2
+test_for_user $user
+if (( $? != 0 )); then        
+	echo "$user not found! exiting..."
+        exit 3
 fi
 
 
-passwd_reset=$(reset_password $user)
-if (( $passwd_reset != 0 )); then
+reset_password $user
+if (( $? != 0 )); then
 	echo "password for $user could not be reset"
-	exit 2
+	exit 3
 fi
 
-passwd_expire=$(expire_password $user)
-if (( $passwd_expire != 0 )); then
+expire_password $user
+if (( $? != 0 )); then
 	echo "WARNING:Password for $user has been reset to freegeek. It will not expire"
 	exit 1
 else
diff --git a/tstools_package/ts_reset_windowmanager b/tstools_package/ts_reset_windowmanager
--- a/tstools_package/ts_reset_windowmanager
+++ b/tstools_package/ts_reset_windowmanager
@@ -34,17 +34,17 @@ done
 if [[ -z $user ]]; then
         user=$EUID
 else
-	uid_test=$(test_for_uid $user)
-	if [[ -z $uid_test ]]; then
-		echo "$user not found! exiting..."
-		exit 2
-	else
-		root_test=$(test_for_root)
-		if [[ $root_test -ne 0 ]]; then
-			echo "You are not root! exiting..."
-			exit 2	
-		fi
+	test_for_user $user
+	if (( $? != 0 )); then
+        	echo "$user not found! exiting..."
+        	exit 3
 	fi
+
+	test_for_root
+	if [[ $? -ne 0 ]]; then
+		echo "You are not root! exiting..."
+		exit 3	
+		fi
 fi
 
 ### reset desktop ###
@@ -57,7 +57,7 @@ for setting in /apps/compiz /apps/metacity /desktop/gnome/session /schemas/deskt
 do	
 	$GCONF_RESET $setting 
 	if [[ $? -ne 0 ]]; then
-        	echo "gconf failed to reset" 
+        	echo "gconf failed to reset $setting" 
         	EXIT=1
 	fi
 done
