addded test for root

diff --git a/tstools_package/ts_mount b/tstools_package/ts_mount
--- a/tstools_package/ts_mount
+++ b/tstools_package/ts_mount
@@ -1,5 +1,9 @@
 #! /bin/bash
-
+if ! test_for_root; then
+        echo "Could not proceed"
+        echo "are you root?"
+        exit 3
+fi
 fdisk -l | while read line ;do 
 	disk=$(echo $line | awk '{print $1}' | egrep ^/dev.*[1-9]$ )
 	if [[ -n $disk ]]; then 
