fixed option processing/case statement for non matches

diff --git a/tstools_package/ts_network_backup b/tstools_package/ts_network_backup
--- a/tstools_package/ts_network_backup
+++ b/tstools_package/ts_network_backup
@@ -54,9 +54,10 @@ source $NB_FUNCTIONS
 
 ### MAIN ###
 
-#if declare -p break_value; then
-#                exit 3
-#        fi
+if [[ -z $1 ]]; then
+		help
+                exit 1
+        fi
 
 while getopts ":hc:r:l:a:A:p:du" option; do
        case $option in
@@ -96,13 +97,15 @@ while getopts ":hc:r:l:a:A:p:du" option; do
 		   path="${cut_path}/home"
 		   chroot_path="chroot $ext_path"
 		;;
-		\?)
-		   help exit 1
-		;;
-	#	*) help
-         #           exit 1
-         #       ;;
-        esac
+        	\?)
+      		   echo "Invalid option: -$OPTARG" >&2
+      		   exit 1
+      		;;
+    		:)
+      		   echo "Option -$OPTARG requires an argument." >&2
+      		   exit 1
+      		;;
+		esac
 done
 
 #sanity checks
@@ -113,7 +116,7 @@ if ! test_for_root ; then
 fi
 # if this machine is tsdata a path must be supplied
 # otherwise some dumbass will back up the wrong thing
-if [[ ! $ext_path && $HOSTNAME = tsdata ]]; then
+if [[ ! $ext_path && $HOSTNAME = "tsdata" ]]; then
 	echo 'YOU MUST USE THE -p OPTION TO SPECIFY THE PATH OF THE 
 DIRECTORY YOU WISH TO BACKUP WHEN YOU ARE ON TSDATA!!!'
 	exit 3
