added create backup control logic

diff --git a/tstools_package/ts_network_backup b/tstools_package/ts_network_backup
--- a/tstools_package/ts_network_backup
+++ b/tstools_package/ts_network_backup
@@ -3,14 +3,20 @@
 #!/bin/bash
 help(){
         cat <<EOF 
-Usage: ts_network_backup  [OPTION]
+Usage: ts_network_backup  [OPTION(S)]
 Create or restore network backup.
 
         -h              	prints this message
+	-l log file		be careful not to use the same path for backing
+				up and restoring, or the  log file may get 
+				overwritten.
         -c ticket number 	create network backup
-	-r backup directory 	restore network backup. The backup directory should be in the foramt date-ticket_number.
-	-d 			Data only. Use of this option is strongly discouraged.
-	-u 			Users and data only. Use of this option is discouraged.		
+	-r backup directory 	restore network backup. The backup directory 
+				should be in the format date-ticket_number.
+	-d 			Data only. 
+				Use of this option is strongly discouraged.
+	-u 			Users and data only. 
+				Use of this option is discouraged.		
 	Use this to create or restore network backups. By default it will attempt to restore users, their data and settings, and the progams installed on the machine. 
 EOF
         exit 0
@@ -31,6 +37,9 @@ source $FUNCTIONS
 # script specific functions
 
 backup_paswords(){
+	groupfile=$1 
+	passwordfile=$2
+	shadowfile=$3
 	cat /etc/passwd| while read line ; do 
 		user=$(echo $line | awk -F : '{print $1}')
 		user_uid=$(echo $line | awk -F : '{print $3}')
@@ -39,12 +48,12 @@ backup_paswords(){
 			# unless user is a nobody :)
 			if [[ ! $user == "nobody" ]]; then
 				# gets lists of groups user belongs to
-				echo "$user: $(id $user)" >>$group_file
-				echo $line >>$password_file
+				echo "$user: $(id $user)" >>$groupfile
+				echo $line >>$passwordfile
 				# /etc/shadow contains the date of last password
 				# change. Having this be older than the install
 				# should not be a problem, but noting just in case
-				grep -e ^$user: /etc/shadow >>$shadow_file
+				grep -e ^$user: /etc/shadow >>$shadowfile
 			fi
 		fi
 	done
@@ -93,7 +102,7 @@ restore_passwords(){
 
 backup_apt(){
 	if  ! dpkg --get-selections > $dpkg_file ; then
-		echo 2
+		echo $?
 	else
 		echo 0
 	fi 
@@ -101,7 +110,7 @@ backup_apt(){
 
 restore_apt(){
         if  ! dpkg --set-selections < $dpkg_file ; then
-                exit=2
+                exit=$?
         else
                 exit=0
         fi
@@ -111,7 +120,7 @@ restore_apt(){
 
 restore_packages(){
 	if  ! apt-get -u dselect-upgrade  ; then
-                exit=2
+                exit=$?
         else
                 exit=0
         fi
@@ -122,7 +131,7 @@ restore_packages(){
 
 backup_config(){
        if  ! tar -cvzf /home/etc_backup.tar.gz /etc/; then
-                exit=2
+                exit=$?
         else
                 exit=0
         fi
@@ -131,15 +140,11 @@ backup_config(){
 
 }
 
-check_log_write(){
-	if [[ $1 ]]; then
-		log_file=$1
-	else
-		log_file=/home/backup.log
-	fi
-
-	if ! touch $log_file; then
-		exit=2
+check_file_write(){
+	file=$1
+	
+	if ! touch $file; then
+		exit=$?
 	else
 		exit=0
 	fi
@@ -158,7 +163,7 @@ create_backup(){
 	fi	
 	
 	if ! $RSYNC; then
-                exit=2
+                exit=$?
         else
                 exit=0
 	fi
@@ -176,7 +181,7 @@ restore_backup(){
 	fi
 
         if ! $RESTORE; then
- 		exit=2
+ 		exit=$?
         else
                 exit=0
         fi
@@ -187,20 +192,25 @@ restore_backup(){
 
 ### MAIN ###
 
-while getopts ":hc:r:du" option; do
-        case $option in
+while getopts ":hl:c:r:du" option; do
+       case $option in
                 h) help
                    exit 0
                 ;;
                 c) create_backup="true"
                    ticket_number=$OPTARG
 		;;
+		l) use_log="true"
+		   log_file=$OPTARG
 		r) restore_backup="true"
                    backup_dir=$OPTARG
 		;;
-		d) data_only="true"
+		d) no_apt="true"
+		   no_user_passwords="true"
+		   data_only="true"
 		;;
-		u) users_and_data_only="true"
+		u) no_apt="true"
+		   users_and_data_only="true"
 		;;
                 /?) help
                     exit 1
@@ -209,21 +219,30 @@ while getopts ":hc:r:du" option; do
 	done
 
 #sanity checks
-if [[ $create_backup ]] && [[ $restore_backup ]]; then 
+if [[ $create_backup  &&  $restore_backup ]]; then 
 	echo "Only one of the c or r options can be used";
 	exit 2
 fi
 
-if [[ $create_backup ]] && [[ ! $ticket_number ]]; then 
+
+if [[ ! $create_backup && ! $restore_backup ]]; then 
+        echo "One of the c or r options must  be used";
+        exit 2
+fi
+
+if [[ $create_backup  &&  ! $ticket_number ]]; then 
         echo "You must supply a ticket number with the c option";
         exit 2
 fi
 
-if [[ $restore_backup ]] && [[ ! $backup_dir ]]; then
+if [[ $restore_backup && ! $backup_dir ]]; then
         echo "You must supply a backup directory with the r option";
         exit 2
 fi
-
+if [[ $data_only  &&  $users_and_data_only ]]; then
+        echo "The u or d options are mutually exclusive";
+        exit 2
+fi
 root_test=$(test_for_root)
 if [[ $root_test -ne 0 ]]; then
         echo "Could not proceed!"
@@ -231,13 +250,53 @@ if [[ $root_test -ne 0 ]]; then
         exit 2
 fi
 
+# 
 
-# create
-#rsync -avzh home/ tsbackup@tsbackup:/var/tsbackup/[date-ticketnumber] 2>rsync.out 
-#  dpkg --get-selections > dpkg.out 
 
-# restore
-#  sudo rsync -avzh  tsbackup@tsbackup:/var/tsbackup/[date-ticketnumber] /home
-#dpkg --set-selections < dpkg.out
-#apt-get -u dselect-upgrade
-
+if [[ $create_backup ]]; then
+	# unless no_apt is set back up record of packages installed
+	if [[ ! $no_apt ]]; then
+		apt_write=$(check_file_write $dkpg_file)
+		if [[ $apt_write -ne 0 ]] ; then
+			echo "Couldn't write to $dpkg_file. Check permissions?"
+			exit 3
+		fi
+		apt_backup=$(backup_apt)
+		if [[ $apt_backup -ne 0]] ; then
+			echo "Backing up package files list failed!"
+			eho "dpkg --get-selections exited with error code $apt_backup" 
+			exit 2
+		fi
+	fi 
+	
+	if [[ ! $no_user_passwords ]]; then
+		# check we can wrtite to the backup files
+		declare -a failarray
+		for file in "$group_file" "$password_file" "$shadow_file"; do
+			writecheck=$(check_file_write "$file")
+			if [[ writecheck -ne 0 ]]; then
+				# if we cant write to file add to array		
+				failarray=( ${failarray[@]-} $(echo "$file") )				fi			
+		done
+		# check length of failarray if >0 then something failed
+		if [[ ${#failarray[@]} -ne 0 ]]; then
+			echo -n "error writing to "
+			for name in ${failarray[@]}; do
+				echo -n "$name"
+			done
+			exit 3 
+		if 
+		# difficult to check except by checking write  (as above)
+		backup_paswords
+	fi
+	config_check=$(backup_config)
+	if [[ config_check -ne 0 ]]; then
+		echo "Could not backup /etc"
+		exit $config_check
+	fi 
+	backup_check=$(create_backup)
+	if [[ backup_check -ne 0 ]]; then
+		echo "Could not backup data!!!"
+		exit $backup_check
+	fi
+fi
