root test

diff --git a/tstools_package/ts_revert_passwords b/tstools_package/ts_revert_passwords
--- a/tstools_package/ts_revert_passwords
+++ b/tstools_package/ts_revert_passwords
@@ -33,7 +33,11 @@ while getopts ":hp:e:" option; do
                 ;;
         esac
 done
-
+if ! test_for_root; then
+        echo "Could not proceed"
+        echo "are you root?"
+        exit 3
+fi
 if ! revert_check=$(revert_passwords $path $extension); then
 	echo $revert_check
 	exit 3
