edited for consistency

diff --git a/tstools_package/ts_reset_windowmanager b/tstools_package/ts_reset_windowmanager
--- a/tstools_package/ts_reset_windowmanager
+++ b/tstools_package/ts_reset_windowmanager
@@ -1,7 +1,7 @@
 #!/bin/bash
 help(){
         cat <<EOF 
-        usage ts_reset_windowmanger [OPTION]
+        usage ts_reset_ windowmanger [OPTION]
         -h              prints this message
         -u [USERNAME]   specify the user whose desktop will be reset.
         -p /path/to/mountpoint        The directory where the target file system is mounted. Use this if you are working on an external or mounted  drive e.g. a drive mounted from a system rescue cd.
@@ -36,17 +36,14 @@ done
 if [[ -z $user ]]; then
         user=$USER
 else
-	test_for_user $user $path
-	if (( $? != 0 )); then
+	if ! test_for_root; then
+  	      echo "Could not proceed"
+        	echo "are you root?"
+       		exit 3
+	elif ! test_for_user $user $path; then
         	echo "$user not found! exiting..."
         	exit 3
 	fi
-
-	test_for_root
-	if [[ $? -ne 0 ]]; then
-		echo "You are not root! exiting..."
-		exit 3	
-		fi
 fi
 
 ### reset desktop ###
