debug2

diff --git a/tstools_package/ts_reset_windowmanager b/tstools_package/ts_reset_windowmanager
--- a/tstools_package/ts_reset_windowmanager
+++ b/tstools_package/ts_reset_windowmanager
@@ -61,6 +61,13 @@ do
 	else
 		echo "success: $setting"
 	fi
+        if ! rm -rf /home/$user/.gconf/$setting; then
+                echo "gconf failed to remove $setting" 
+                EXIT=3
+        else
+                echo "success: $setting"
+        fi
+
 done
 
 if [[ -z  $EXIT ]] ; then
