removed unecessary step

diff --git a/tstools_package/ts_reset_panel b/tstools_package/ts_reset_panel
--- a/tstools_package/ts_reset_panel
+++ b/tstools_package/ts_reset_panel
@@ -59,10 +59,10 @@ if ! reset_gconf $user /apps/panel $path; then
 	echo "gconf failed to reset panel" 
 	exit 3
 fi
-if ! rm -rf /home/$user/.gconf/apps/panel; then
-        echo "gconf failed to reset" 
-        exit 3
-fi
+#if ! rm -rf /home/$user/.gconf/apps/panel; then
+#        echo "gconf failed to remove /home/$user/.gconf/apps/panel" 
+#        exit 3
+#fi
 
 if [[ ! $path ]] ; then
 	if ! pkill gnome-panel ; then
