minor optimization

diff --git a/tstools_package/ts_rechown b/tstools_package/ts_rechown
--- a/tstools_package/ts_rechown
+++ b/tstools_package/ts_rechown
@@ -33,23 +33,22 @@ done
 
 
 
-test_for_root
-if [[ $? -ne 0 ]]; then
+if ! test_for_root; then
         echo "You are not root! exiting..."
         exit 3
 fi
 
-test_for_user $user
-if (( $? != 0 )); then
-        echo "$user not found! exiting..."
-        exit 3
+if [[ -z $user ]]; then 
+        user=$(choose_username)
 fi
 
 
+if ! test_for_user $user; then
+        echo "$user not found! exiting..."
+        exit 3
       
 ### reset ownership ###
-
-if ! chown -R $user.$user /home/$user ; then
+elif ! chown -R $user.$user /home/$user ; then
 	echo "WARNING: Failed to change ownership for some or all files!"
 	exit 3
 else
