edited for consistency

diff --git a/tstools_package/ts_reset_gnome b/tstools_package/ts_reset_gnome
--- a/tstools_package/ts_reset_gnome
+++ b/tstools_package/ts_reset_gnome
@@ -61,17 +61,14 @@ done
 if [[ -z $user ]]; then
         user=$USER
 else
-	test_for_user $user $path
-	if (( $? != 0 )); then
+	if ! test_for_root; then
+        	echo "Could not proceed"
+        	echo "are you root?"
+        	exit 3
+	elif ! test_for_user $user $path; then
         	echo "$user not found! exiting..."
         	exit 3
 	fi
-
-	test_for_root
-	if [[ $? -ne 0 ]]; then
-		echo "You are not root! exiting..."
-		exit 3	
-		fi
 fi
 
 if [[ $nuke_from_orbit ]]; then
