added option for externally mounted disk

diff --git a/tstools_package/ts_reset_panel b/tstools_package/ts_reset_panel
--- a/tstools_package/ts_reset_panel
+++ b/tstools_package/ts_reset_panel
@@ -5,6 +5,9 @@ help(){
         -h              prints this message
         -u [USERNAME]   specify the user whose panels will be reset,
 			defaults to the user running the command.
+        -p /path/to/mountpoint        The directory where the target file system is mounted. Use this if you are working on an external or mounted  drive e.g. a drive mounted from a system rescue cd. 	Implies -u 
+
+
 	Resets gnome panels to their default state. 
 EOF
         exit 0
@@ -18,13 +21,15 @@ source $FUNCTIONS
 
 ### process options ###
 
-while getopts ":hu:" option; do
+while getopts ":hu:p:" option; do
         case $option in
                 h) help
                    exit
                 ;;
                 u) user=$OPTARG
 		;;
+                p) path="$OPTARG"
+                ;;
                 \?) help
                     exit
                 ;;
@@ -35,7 +40,7 @@ done
 if [[ -z $user ]]; then
         user=$USER
 else
-        test_for_user $user
+        test_for_user $user $path
         if (( $? != 0 )); then
                 echo "$user not found! exiting..."
                 exit 3
@@ -51,7 +56,7 @@ fi
 # reset panel second stage maybe unnecessary need to test
 
 # set appropriate command and options
-if ! reset_gconf $user /apps/panel; then
+if ! reset_gconf $user /apps/panel $path; then
 	echo "gconf failed to reset panel" 
 	exit 3
 
@@ -61,9 +66,11 @@ if ! reset_gconf $user /apps/panel; then
 #        EXIT=1
 #fi
 
-elif ! pkill gnome-panel ; then
-        echo "failed to restart gnome-panel" 
-        exit 3
+if [[ ! $path ]] 
+	if ! pkill gnome-panel ; then
+        	echo "failed to restart gnome-panel" 
+        	exit 2
+	fi
 else
 	exit 0
 fi
