bug fix!

diff --git a/tstools_package/ts_reset_panel b/tstools_package/ts_reset_panel
--- a/tstools_package/ts_reset_panel
+++ b/tstools_package/ts_reset_panel
@@ -34,21 +34,24 @@ done
 #set/check user
 if [[ -z $user ]]; then
         user=$EUID
-fi
+else
+        test_for_user $user
+        if (( $? != 0 )); then
+                echo "$user not found! exiting..."
+                exit 3
+        fi
 
-if ! test_for_user $user ; then
-        echo "$user not found! exiting..."
-        exit 3
-elif ! test_for_root; then
-	echo "You are not root! exiting..."
-	exit 3  
+        test_for_root
+        if [[ $? -ne 0 ]]; then
+                echo "You are not root! exiting..."
+                exit 3
+                fi
 fi
-
 
 # reset panel second stage maybe unnecessary need to test
 
 # set appropriate command and options
-if ! set_gconf $user /apps/panel; then
+if ! reset_gconf $user /apps/panel; then
 	echo "gconf failed to reset panel" 
 	exit 3
 
